---

- name: Ensure local directory
  ansible.builtin.file:
    state: directory
    mode: '0755'
  with_nested: "{{ dirs }}"
  vars:
    dirs:
      - /usr/local/share
        - /gnome-shell
          - /extensions
