---

- name: Ensure local directory
  ansible.builtin.file:
    state: directory
    mode: '0755'
    path: "/usr/local/share/gnome-shell/extensions"

- name: Install argos from git
  ansible.builtin.git:
    repo: "https://github.com/p-e-w/argos.git"
    dest: "/usr/local/share/gnome-shell/extensions"

- name: Install (de-) activate script for user
  ansible.builtin.copy:
    src: "usr/local/bin/toggle_argos"
    dest: "/usr/local/bin/toggle_argos"
    mode: '0755'
