#!/usr/bin/bash
echo "mgmt"
echo "---"
for i in suspend hibernate suspend-then-hibernate
do
  echo "$i | terminal=false bash='sudo /lib/systemd/systemd-sleep $i; /usr/bin/xdg-screensaver lock'"
done
echo "---"
echo "update config | terminal=true bash='sudo mlc-ansible-pull -v -r hourly; sleep 1; exit'"
echo "update software | terminal=true bash='sudo update-system; sleep 1; exit'"

