#!/usr/bin/bash
RANDR=/usr/local/bin/gnome-randr
BUILTIN="eDP-1"

echo "res"
echo "---"
previous="NONE"
$RANDR query $BUILTIN | sed -ne "s/^ *\([0-9][0-9]*x[0-9][0-9]*@[0-9.]*\).*/\1/p" | sort -rn | while read line
do
  short=${line%@*}
  if [[ "${short}" != "${previous}" ]]
  then
    echo "$short | terminal=false bash='$RANDR modify $BUILTIN --mode $line'"
  fi
  previous=$short
done
